name: test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: set up go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: install session manager plugin
      run: |
        curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
        sudo dpkg -i session-manager-plugin.deb

    - name: install dependencies
      run: go mod tidy

    - name: run tests
      run: go test ./... -v